### ISSUE TITLE
*Stop Shame Reaction* Is not working.

### ISSUE THREAD

**Issue by Wolf1030** [ManlyMarco/KoikatuCheatTools#15]
So, going into the dressing room or showers and pressing the button does not stop the embarrassed  reactions from occurring. For NPCs already in the map or new ones entering.

**Comment by ManlyMarco** [comment]
> I'm also having this issue. The command works once inside of a certain area (bathroom, locker room, ect) but stops working as soon as I leave the area.

That's exactly what it's meant to do.
